In [3]:
import pandas as pd

df = pd.read_csv("insurance_data.csv")

df

      age  gender     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   gender    1338 non-null   str
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   str
 5   region    1338 non-null   str
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), str(3)
memory usage: 73.3 KB

In [5]:
df['region'].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [6]:
gender_dict={'male':1, 'female':2}
df['gender'] = df['gender'].map(gender_dict)

In [7]:
smoker_dict={'yes':1, 'no':2}
df['smoker'] = df['smoker'].map(smoker_dict)

In [8]:
region_dict={'northeast':1, 'southeast':2, 'southwest':3, 'northwest':4}
df['region'] = df['region'].map(region_dict)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   gender    1338 non-null   int64
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   int64
 5   region    1338 non-null   int64
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(5)
memory usage: 73.3 KB

In [10]:
df

      age  gender     bmi  children  smoker  region      charges
0      19       2  27.900         0       1       3  16884.92400
1      18       1  33.770         1       2       2   1725.55230
2      28       1  33.000         3       2       2   4449.46200
3      33       1  22.705         0       2       4  21984.47061
4      32       1  28.880         0       2       4   3866.85520
...   ...     ...     ...       ...     ...     ...          ...
1333   50       1  30.970         3       2       4  10600.54830
1334   18       2  31.920         0       2       1   2205.98080
1335   18       2  36.850         0       2       2   1629.83350
1336   21       2  25.800         0       2       3   2007.94500
1337   61       2  29.070         0       1       4  29141.36030

[1338 rows x 7 columns]

In [11]:
x=df.drop('charges', axis=1)
y =df[['charges']]

In [12]:
y

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
x

      age  gender     bmi  children  smoker  region
0      19       2  27.900         0       1       3
1      18       1  33.770         1       2       2
2      28       1  33.000         3       2       2
3      33       1  22.705         0       2       4
4      32       1  28.880         0       2       4
...   ...     ...     ...       ...     ...     ...
1333   50       1  30.970         3       2       4
1334   18       2  31.920         0       2       1
1335   18       2  36.850         0       2       2
1336   21       2  25.800         0       2       3
1337   61       2  29.070         0       1       4

[1338 rows x 6 columns]

In [14]:
from sklearn.model_selection import train_test_split

# Assuming you want to split y into train and test sets
x_train , x_test , y_train, y_test = train_test_split(x , y, test_size=0.2, random_state=42)

y_test

          charges
764    9095.06825
887    5272.17580
890   29330.98315
1293   9301.89355
259   33750.29180
...           ...
109   47055.53210
575   12222.89830
535    6067.12675
543   63770.42801
846    9872.70100

[268 rows x 1 columns]

In [15]:
from sklearn.linear_model import LinearRegression
L=LinearRegression()
L.fit(x_train, y_train)
y_pred=L.predict(x_test)

In [16]:
from sklearn.ensemble import RandomForestRegressor
rgf =RandomForestRegressor()

In [17]:
rgf.fit(x_train, y_train)

e:\Data science\Python\liet_data\Lib\site-packages\sklearn\base.py:1336: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [18]:
rgf.score(x_test, y_test)

0.8581225625786091

In [19]:
rgf.predict(x_test)

array([ 9494.1941362 ,  5201.26083286, 28332.914757  , 13228.1060087 ,
       34575.4291618 ,  8613.9384731 ,  2081.1454705 , 15062.5906694 ,
        6284.4084389 , 11409.9860947 , 19408.6713399 ,  6991.3816335 ,
        5555.3740998 , 46027.7024228 , 48400.9088307 , 45262.0651128 ,
       10004.7088039 , 42780.2502244 ,  9061.2789877 , 24201.6863658 ,
        5144.3283187 ,  8883.1256878 ,  1985.41230652,  2377.5674443 ,
       11638.4177407 , 11758.922262  , 13197.6308583 ,  5524.5830699 ,
       10641.7325416 ,  5820.51125897,  7746.4267495 , 11782.5351495 ,
        2850.5598476 ,  5924.0123607 ,  3633.4418384 , 12348.5065285 ,
        2934.5197155 ,  8440.1235209 , 23859.8286375 , 39454.8143014 ,
        7030.3572507 ,  3401.274703  , 13109.0628267 , 14567.9716407 ,
        6525.7848624 , 14124.7605327 , 18040.8104689 ,  5497.3898102 ,
       42056.5625173 ,  6806.7990813 , 14093.9234001 ,  2089.5319081 ,
        6693.2400339 ,  1748.4447185 , 12171.136538  , 10223.1658752 ,
        3474.0997555 , 45002.8865109 , 13020.6353234 , 15868.1285478 ,
       13859.5216635 ,  8352.9020507 , 18391.6357817 ,  7521.5585696 ,
       12282.906511  ,  5036.9086705 , 18809.9762092 , 14320.8145345 ,
        5786.5929683 ,  2290.1691625 ,  7402.2601794 , 10493.0497568 ,
       10373.4914643 , 11631.6495032 ,  8798.7388955 ,  5002.4373415 ,
        9251.894921  , 12673.8112366 ,  4256.0695665 ,  9320.4319428 ,
        2614.2326342 , 27782.4439387 ,  6134.2130275 , 38268.8791517 ,
       40506.473949  , 41729.5446519 ,  6209.4161713 , 12529.9503926 ,
        8724.5202272 , 16033.5278187 , 19552.6550197 , 26325.2001648 ,
       29059.0403029 ,  5009.8627715 , 44781.3229318 ,  7018.3927935 ,
       20797.9970111 ,  3065.0173997 , 17570.2921963 , 12356.5406032 ,
        5256.5965876 ,  1902.29646417,  6214.4327028 , 14641.4529968 ,
       13861.3488632 ,  7167.3279585 , 10171.5885461 , 23045.8368444 ,
        1803.7954638 , 24022.0671953 ,  1306.6877455 ,  3654.8277969 ,
       12325.6802084 , 39427.0339881 , 10896.7788334 ,  6241.8951181 ,
       12817.7058685 , 24659.4609239 ,  7583.1170577 ,  7307.9985585 ,
        8623.2233842 ,  8097.6394493 , 15653.8498924 ,  2115.353831  ,
        5417.8537745 ,  7518.4023395 , 13675.9321601 , 11621.1150867 ,
       15951.1562335 ,  3954.8618984 ,  4112.665895  ,  7088.4561155 ,
        7208.6008801 , 13135.6569779 ,  6092.0439135 , 25941.9827558 ,
        5777.1608864 , 37553.6604547 , 47056.65029   , 39063.6909291 ,
        5068.4502314 , 12977.4474249 ,  2571.474162  , 16712.7306899 ,
        2543.687842  , 24284.3967559 ,  6092.3376018 ,  4056.5171633 ,
       11303.5757698 ,  5235.5209661 , 51726.8080168 ,  9893.3341202 ,
        1842.3547023 , 45283.2148539 ,  5979.3068617 ,  5082.8135608 ,
       13805.4490756 , 10625.9459768 , 35414.0907214 , 39715.4585223 ,
       14664.0265906 ,  3869.0660512 , 20567.7784929 ,  4241.841491  ,
        6020.5669479 ,  8374.8281978 , 48442.3452996 , 45283.6356501 ,
       40506.6487449 ,  3813.8147961 , 10135.4755527 ,  7178.3508045 ,
        7905.4050236 ,  4532.3797233 ,  2259.1123315 , 23561.6793283 ,
       16839.567458  , 14241.6099184 , 16837.8993283 , 11581.984289  ,
       28069.5280677 ,  7952.6925111 , 10073.4250441 ,  6871.6477657 ,
        6650.0282997 ,  4185.8685236 ,  4996.2992114 ,  5683.9810973 ,
        9490.4053865 , 13222.3273332 ,  4313.8375337 ,  4195.71614825,
        3431.4452316 , 46931.2766153 , 13156.557966  , 10024.3150833 ,
        4015.1777518 , 16719.9242068 ,  2490.8225445 , 12261.8405244 ,
        3703.4735934 , 23902.272321  , 10542.1318247 , 10012.9604201 ,
       19157.9490548 , 18511.8544943 , 13011.7012324 ,  9477.9901462 ,
       11091.6172145 ,  4302.4881321 , 14061.0997036 , 13016.8037698 ,
       10847.661837  , 19237.4100381 ,  8348.2246634 ,  4308.4272669 ,
        4911.4076534 , 14027.6879306 , 14098.9790658 ,  6557.8469725 ,
        2120.7103145 ,  8696.8102261 ,  8777.4376665 , 45221.0404736 ,
        2108.6222021 , 38650.8164569 ,  1754.8947365 ,  2161.13565042,
        9566.084329  , 10741.0509199 ,  2558.1131743 ,  9735.315334  ,
        6511.3036154 , 25258.8710039 , 11843.3932981 ,  9346.1554149 ,
        4981.2144789 ,  7600.7474596 , 44554.3552931 ,  2661.39299   ,
       13626.056084  , 40929.1096976 ,  3244.4125601 ,  3746.7382385 ,
        1631.9847505 ,  4112.8791372 ,  4917.4952305 ,  4271.52697   ,
       13817.1923561 ,  2462.5666941 ,  2080.61510917,  7816.075714  ,
        3645.5596763 , 11575.06532   ,  4892.6256038 ,  4501.8148866 ,
       12622.163834  ,  5659.0760064 ,  9269.3058607 ,  6610.2710088 ,
        7496.4988915 , 14865.8965434 , 20395.2306112 , 47098.9524159 ,
       12721.9711928 ,  6350.5205565 , 46674.2216899 ,  9741.00022   ])

In [20]:
y_test

          charges
764    9095.06825
887    5272.17580
890   29330.98315
1293   9301.89355
259   33750.29180
...           ...
109   47055.53210
575   12222.89830
535    6067.12675
543   63770.42801
846    9872.70100

[268 rows x 1 columns]

In [21]:
L.score(x_test, y_test)

0.7809227350368881

In [22]:
L.score(x_train, y_train)

0.7412317448754484

In [23]:
y_pred

array([[ 8755.82313828],
       [ 6773.44053983],
       [36593.41289767],
       [ 9234.61837437],
       [26653.78875406],
       [11023.81883547],
       [  -54.57524623],
       [16550.90782803],
       [  943.09389447],
       [10969.31911393],
       [28446.87757793],
       [ 9101.48647876],
       [ 5521.55566801],
       [38561.82969537],
       [40406.32176169],
       [37274.21675775],
       [15377.51348785],
       [36094.30131663],
       [ 9392.83639548],
       [31189.3792777 ],
       [ 4217.8521542 ],
       [10403.09646661],
       [ 2647.40176605],
       [ 6759.04999844],
       [11045.77740792],
       [12664.66482285],
       [14739.97647605],
       [ 5872.38690264],
       [ 9736.31362139],
       [ 2434.96288438],
       [ 9418.29542073],
       [12767.51360488],
       [ 4758.61684136],
       [ 3228.37386556],
       [ 4748.23695592],
       [12672.30188145],
       [ 2290.20391646],
       [ 9095.69327834],
       [33035.05447843],
       [32790.71036115],
       [ 4215.68495284],
       [ 4030.31307484],
       [14369.70821405],
       [11196.06645633],
       [ 8989.34373467],
       [12423.06063899],
       [ 4953.99004295],
       [ 3493.56579624],
       [35704.25610603],
       [ 9337.66784671],
       [16034.13915412],
       [ 2613.50362031],
       [11959.59250687],
       [ 1252.38075623],
       [13616.05560568],
       [12304.03986159],
       [ 4123.01701419],
       [31839.97230482],
       [13571.52328883],
       [12593.65813438],
       [14433.23880313],
       [10631.98206655],
       [16609.49340496],
       [ 7532.04526806],
       [11559.9555092 ],
       [ 3809.65595083],
       [26986.0696401 ],
       [11252.517785  ],
       [ 1919.68167309],
       [ 6394.12066875],
       [10400.61813363],
       [11342.26114525],
       [11203.24691167],
       [ 9418.65278208],
       [12144.90043122],
       [ 7000.52714197],
       [ 6970.85722485],
       [10491.62267427],
       [ 6809.16860563],
       [ 9097.91280497],
       [ 3992.41714619],
       [36400.84566041],
       [ 6662.5671489 ],
       [30491.47375782],
       [34869.39832022],
       [34989.78066133],
       [ 7281.17910945],
       [12557.93920714],
       [ 9652.66266049],
       [14714.25976035],
       [17353.95725958],
       [35579.94565267],
       [32790.19231946],
       [ 5955.10485131],
       [32198.49597092],
       [ 9757.66993431],
       [29711.75992005],
       [ 3889.99450414],
       [28078.90701322],
       [ 5623.489058  ],
       [ 5131.74821793],
       [ 2162.51588259],
       [11661.80996527],
       [15322.81873354],
       [11510.36053192],
       [ 4519.28199417],
       [10165.95621562],
       [32060.60620204],
       [ -269.29991792],
       [33143.55060663],
       [ 3530.00924623],
       [10281.64396858],
       [14031.08775069],
       [31339.17533955],
       [11187.14331232],
       [ 4184.90232819],
       [12867.87039469],
       [32119.28683198],
       [ 8406.02136367],
       [ 2983.35028842],
       [ 8134.54169659],
       [10281.56536892],
       [14873.77203964],
       [ 5848.79278142],
       [ 3556.69969645],
       [ 9914.36048281],
       [11101.9392869 ],
       [10871.14463044],
       [14645.21859173],
       [ 7569.15238604],
       [ 5647.5646621 ],
       [ 9466.80584401],
       [ 9545.42329128],
       [12180.8781648 ],
       [ 8584.09203964],
       [15561.2205685 ],
       [ 8093.65670352],
       [32074.74814072],
       [35390.66208173],
       [31308.27633717],
       [ 5748.63518785],
       [12296.37121926],
       [ 6219.63031988],
       [14204.61601882],
       [ 2797.98412334],
       [33298.26400691],
       [ 6018.00165251],
       [ 5315.91342587],
       [14004.87190652],
       [ 7227.69719414],
       [38314.21486313],
       [ 2806.99224142],
       [ 6030.77113694],
       [31378.03860291],
       [11165.43026958],
       [ 8164.66339199],
       [14531.56444578],
       [10081.66832007],
       [27308.01720224],
       [33157.22570846],
       [14275.00681848],
       [ 1431.532127  ],
       [13518.88847131],
       [ 2011.12539784],
       [ 5719.33426046],
       [11772.81321606],
       [40001.29914301],
       [36189.53020129],
       [33720.74483106],
       [ 4164.17381135],
       [ 7828.43461386],
       [ 8916.27185545],
       [12059.93350482],
       [ 4576.20914816],
       [ 2346.11569866],
       [32421.12529349],
       [25404.19383574],
       [17652.42961886],
       [26237.93769476],
       [ 9941.53521002],
       [37005.23398421],
       [ -583.27687009],
       [ 6612.90268511],
       [ 8021.86717522],
       [ 4193.72808402],
       [ 4772.33609567],
       [ 5662.33652949],
       [ 4600.93016853],
       [15295.59028629],
       [10880.98499481],
       [ 7157.65756149],
       [ 2251.5830061 ],
       [ 1324.47616218],
       [32163.97594456],
       [16598.38851241],
       [12226.9582922 ],
       [ 1027.82092774],
       [12282.97114464],
       [ 1319.94177702],
       [ 9061.15636963],
       [ 1653.60517086],
       [33655.21561892],
       [10986.11128629],
       [ 2353.20315726],
       [25945.98874618],
       [26633.88240457],
       [ 9190.59912413],
       [ 1604.46029819],
       [13427.19642274],
       [ 1488.95036138],
       [10770.77900636],
       [10893.07161916],
       [16497.34261279],
       [27126.2155978 ],
       [ 7266.79618715],
       [ 4935.89101824],
       [ 6119.39841484],
       [13526.76900334],
       [11414.61952103],
       [ 8575.80473979],
       [ 4776.69898371],
       [11932.13917216],
       [13972.82287292],
       [35957.21236041],
       [ 3848.50342232],
       [29151.12493244],
       [ -550.6848898 ],
       [ 2579.62329729],
       [11321.30494684],
       [15842.46920729],
       [ 5400.4107213 ],
       [ 6720.57139199],
       [ 4190.72571756],
       [31612.9214245 ],
       [ 7071.07044918],
       [12605.78888125],
       [ 5334.62658741],
       [ 9775.60439409],
       [36460.44876469],
       [ 4650.91934486],
       [ 9519.41357555],
       [31387.79274853],
       [ 5402.32752159],
       [ 4857.42511273],
       [  809.50496205],
       [ 4536.24137546],
       [ 4881.37659531],
       [ 6782.58405061],
       [18770.70928498],
       [-1705.92635644],
       [ 2648.6749784 ],
       [10943.94645754],
       [ 3465.16614724],
       [10020.65178577],
       [ 3419.03341569],
       [ 5355.20991149],
       [12707.79658272],
       [ 5898.12991814],
       [ 8049.68482888],
       [ 7322.44499952],
       [ 8658.75631089],
       [10287.67137917],
       [28066.75410007],
       [39272.54819068],
       [11503.16786501],
       [ 7450.42090824],
       [40989.29063052],
       [12560.00688771]])

In [24]:
y_test

          charges
764    9095.06825
887    5272.17580
890   29330.98315
1293   9301.89355
259   33750.29180
...           ...
109   47055.53210
575   12222.89830
535    6067.12675
543   63770.42801
846    9872.70100

[268 rows x 1 columns]

In [25]:
from sklearn.datasets import load_iris
x , y =load_iris(return_X_y=True  )

In [26]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [27]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
from sklearn.model_selection import train_test_split

# Assuming you want to split y into train and test sets
x_train , x_test , y_train, y_test = train_test_split(x , y, test_size=0.2, random_state=42)

y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [29]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x_train, y_train )

RandomForestClassifier()

In [30]:
rfc.score(x_test, y_test)

1.0

In [31]:
rfc.predict(x_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [32]:
y_test

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [33]:
from sklearn.tree import DecisionTreeRegressor,DecisionTreeClassifier
dtr=DecisionTreeRegressor()
dtr.get_params()

{'ccp_alpha': 0.0,
 'criterion': 'squared_error',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [34]:
dtr.fit(x_train, y_train)

DecisionTreeRegressor()

In [35]:
dtr.score(x_test, y_test)

1.0

In [36]:
dtr.score(x_train, y_train)

1.0

In [37]:
dtr.predict(x_test)

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0.])

In [38]:
dtr.predict(x_test)

array([1., 0., 2., 1., 1., 0., 1., 2., 1., 1., 2., 0., 0., 0., 0., 1., 2.,
       1., 1., 2., 0., 2., 0., 2., 2., 2., 2., 2., 0., 0.])